name: 'Common Lisp Shell Scripting'
description: 'Allows using Lisp code with shebang pointing to Common Lisp implementation.'
inputs:
  lisp:
    description: |
      Path to Common Lisp implementation executable. Supported implementations: SBCL, CCL and ECL.
    required: true
  lisp-scripting-ref:
    required: true
    default: b39535fb1f38b492c9c569574cc16e2a14a469d4
outputs:
  lisps:
    description: "Link to executable for use in shebang string"
    value: ${{ steps.output.outputs.lisps }}
runs:
  using: "composite"
  steps:
    - run: echo "LISP_SCRIPTING_HOME=${{ github.workspace }}/.borodust/lisp-scripting/${{ inputs.lisp-scripting-ref }}/" >> $GITHUB_ENV
      shell: sh
    - uses: actions/checkout@v2
      with:
        repository: borodust/lisp-scripts
        ref: ${{ inputs.lisp-scripting-ref }}
        path: ${{ env.LISP_SCRIPTING_HOME }}
    - run: echo "LISPS=/usr/local/bin/lisps" >> $GITHUB_ENV
      shell: sh
    - run: ${{ env.LISP_SCRIPTING_HOME }}/lisps/install-lisp-script.sh ${{ inputs.lisp }} "$LISPS"
      shell: sh
    - run: echo "${{ env.LISP_SCRIPTING_HOME }}/" >> $GITHUB_PATH
      shell: sh
    - id: output
      run: echo "::set-output name=lisps::$LISPS"
      shell: sh
