name: 'Common Lisp Shell Scripting'
description: 'Allows using Lisp code with shebang pointing to Common Lisp implementation.'
inputs:
  lisp:
    description: |
      Path to Common Lisp implementation executable. Supported implementations: SBCL, CCL and ECL.
    required: true
outputs:
  lisps:
    description: "Link to executable for use in shebang string"
    value: ${{ steps.output.lisps }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: borodust/lisp-scripts
        ref: b39535fb1f38b492c9c569574cc16e2a14a469d4
        path: ${{ github.workspace }}/.boroactions-lisp-scripting/
    - run: echo "LISPS=/usr/local/bin/lisps" >> $GITHUB_ENV
      shell: sh
    - run: ${{ github.workspace }}/.boroactions-lisp-scripting/lisps/install-lisp-script.sh ${{ inputs.lisp }} "$LISPS"
      shell: sh
    - id: output
      run: echo "::set-output name=lisps::$LISPS"
      shell: sh
